$(function () {
  const country = {
    AD: 'By Customer Account',
    AE: 'U.A.E',
    AF: 'Afghanistan',
    AG: 'Antigua',
    AI: 'Anguilla',
    AL: 'Albania',
    AM: 'Armenia',
    AN: 'Neth Ant.',
    AO: 'Angola',
    AQ: 'Antarctica',
    AR: 'Argentina',
    AS: 'American Samoa',
    AT: 'Austria',
    AU: 'Australia',
    AW: 'Aruba',
    AZ: 'Azerbaijan',
    BA: 'Bosnia-Herz',
    BB: 'Barbados',
    BD: 'Bangladesh',
    BE: 'Belgium',
    BF: 'Burkina Faso',
    BG: 'Bulgaria',
    BH: 'Bahrain',
    BI: 'Burundi',
    BJ: 'Benin',
    BM: 'Bermuda',
    BN: 'Brunei',
    BO: 'Bolivia',
    BR: 'Brazil',
    BS: 'Bahamas',
    BT: 'Bhutan',
    BV: 'Bouvet Island',
    BW: 'Botswana',
    BY: 'Belarus',
    BZ: 'Belize',
    CA: 'Canada',
    CC: 'Cocos Islands',
    CD: 'Congo',
    CF: 'Cent Afr',
    CG: 'Congo',
    CH: 'Switzerland',
    CI: 'Ivory',
    CK: 'Cook Islands',
    CL: 'Chile',
    CM: 'Cameroon',
    CN: 'China',
    CO: 'Columbia',
    CR: 'Costa Rica',
    CU: 'Cuba',
    CV: 'Cape Verde',
    CX: 'Christmas Is.',
    CY: 'Cyprus',
    CZ: 'Czech Republic',
    DE: 'Germany',
    DJ: 'Djibouti',
    DK: 'Denmark',
    DM: 'Dominica',
    DO: 'Dominican',
    DZ: 'Algeria',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egypt',
    EH: 'Western Sahara',
    ER: 'Eritrea',
    ES: 'Spain',
    ET: 'Ethiopia',
    EU: 'EUR Countries',
    FI: 'Finland',
    FJ: 'Fiji',
    FK: 'Falkland Is.',
    FM: 'Micronesia',
    FO: 'Faroe Islands',
    FR: 'France',
    GA: 'Gabon',
    GB: 'G.B.',
    GD: 'Grenada',
    GE: 'Georgia',
    GF: 'French Guiana',
    GG: 'Channel Islands',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GL: 'Greenland',
    GM: 'Gambia',
    GN: 'Guinea',
    GO: 'GOLD',
    GP: 'Guadeloupe',
    GQ: 'Equ. Guinea',
    GR: 'Greece',
    GS: 'S Georgia',
    GT: 'Guatemala',
    GU: 'Guam',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HK: 'H.K.',
    HM: 'Heard .McDonald',
    HN: 'Honduras',
    HR: 'Croatia',
    HT: 'Haiti',
    HU: 'Hungary',
    ID: 'Indonesia',
    IE: 'Ireland',
    IL: 'Israel',
    IM: 'Isle of Man',
    IN: 'India',
    IO: 'Br Ind. Oc. Ter',
    IQ: 'Iraq',
    IR: 'Iran',
    IS: 'Iceland',
    IT: 'Italy',
    JE: 'Jersey',
    JM: 'Jamaica',
    JO: 'Jordan',
    JP: 'Japan',
    KE: 'Kenya',
    KG: 'Kyrgyzstan',
    KH: 'Cambodia',
    KI: 'Kiribati',
    KM: 'Comoro',
    KN: 'St Kitts .Nevis',
    KP: 'Korea',
    KR: 'Korea, Rep. of',
    KW: 'Kuwait',
    KY: 'Cayman Islands',
    KZ: 'Kazakstan',
    LA: 'Lao',
    LB: 'Lebanon',
    LC: 'St. Lucia',
    LI: 'Liecht',
    LK: 'Sri Lanka',
    LR: 'Liberia',
    LS: 'Lesotho',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    LV: 'Latvia',
    LY: 'Libya',
    MA: 'Morocco',
    MC: 'Monaco',
    MD: 'Moldova, Rep of',
    MG: 'Madagascar',
    MH: 'Marshall Is.',
    MK: 'Macedonia',
    ML: 'Mali',
    MM: 'Myanmar',
    MN: 'Mongolia',
    MO: 'Macau',
    MP: 'N. Mariana Is.',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MS: 'Monserrat',
    MT: 'Malta',
    MU: 'Mauritius',
    MV: 'Maldives',
    MW: 'Malawi',
    MX: 'Mexico',
    MY: 'Malaysia',
    MZ: 'Mozambique',
    NA: 'Namibia',
    NC: 'New Caledonia',
    NE: 'Niger',
    NF: 'Norfolk Island',
    NG: 'Nigeria',
    NI: 'Nicaragua',
    NL: 'Netherlands',
    NO: 'Norway',
    NP: 'Nepal',
    NR: 'Nauru',
    NU: 'Niue',
    NZ: 'N.Z.',
    OM: 'Oman',
    OT: 'Non-Resident',
    PA: 'Panama',
    PE: 'Peru',
    PF: 'Fr. Polynesia',
    PG: 'Pap. New Guinea',
    PH: 'Philippines',
    PI: 'PLATINUM',
    PK: 'Pakistan',
    PL: 'Poland',
    PM: 'St. Pierre',
    PN: 'Pitcairn',
    PR: 'Puerto Rico',
    PT: 'Portugal',
    PW: 'Palau',
    PY: 'Paraguay',
    QA: 'Qatar',
    RE: 'Reunion',
    RO: 'Romania',
    RS: 'Serbia',
    RU: 'Russian Fed',
    RW: 'Rwanda',
    SA: 'Saudi Arabia',
    SB: 'Solomon Islands',
    SC: 'Seychelles',
    SD: 'Sudan',
    SE: 'Sweden',
    SG: 'Singapore',
    SH: 'St. Helena',
    SI: 'Slovenia',
    SJ: 'Svalbard',
    SK: 'Slovakia',
    SL: 'Sierra Leone',
    SM: 'San Marino',
    SN: 'Senegal',
    SO: 'Somalia',
    SR: 'Suriname',
    SS: 'SILVER',
    ST: 'Sao Tome',
    SV: 'El Salvador',
    SY: 'Syria',
    SZ: 'Swaziland',
    TC: 'Turks . Caicos',
    TD: 'Chad',
    TF: 'Fr. S. Territ.',
    TG: 'Togo',
    TH: 'Thailand',
    TJ: 'Tajikistan',
    TK: 'Tokelau',
    TM: 'Turkmenistan',
    TN: 'Tunisia',
    TO: 'Tonga',
    TP: 'East Timor',
    TR: 'Turkey',
    TT: 'Trinidad Tobago',
    TV: 'Tuvalu',
    TW: 'Taiwan',
    TZ: 'Tanzania',
    UA: 'Ukraine',
    UG: 'Uganda',
    UK: 'U.K',
    UM: 'US Minor Out Is',
    US: 'USA',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VA: 'Vatican',
    VC: 'St. Vincent',
    VE: 'Venezuala',
    VG: 'Virgin Islands',
    VI: 'Virgin Islands',
    VN: 'Vietnam',
    VU: 'Vanuatu',
    WF: 'Wallis .Futuna',
    WS: 'Samoa',
    XA: 'XAU and XAG',
    XE: 'Europa',
    XG: 'Gold',
    XP: 'XPD AND XPT',
    XS: 'Silver',
    XX: 'Worldwide',
    YE: 'Yemen',
    YT: 'Mayotte',
    YU: 'Yugoslavia',
    ZA: 'South Afr',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
  }

  const branch = {
    ho: '001.Main Branch',
    opb: '002.Olympic',
    svb: '003.Sihanouk Ville',
    bbb: '004.Battambang',
    kcb: '005.Kampong Cham',
    cgb: '006.Charles De Gaulle',
    plb: '007.Pailin',
    srb: '008.Siem Reap “SKY”',
    ppb: '009.POIPET',
    kpb: '010.Kampot',
    ssb: '011.Sorya',
    ptb: '012.Banteay Meanchey',
    pct: '013.Pochentong',
    tmb: '014.Takhmao',
    khb: '015.Kampong Chhnang',
    nlb: '016.Neak Loeung',
    scb: '018.Stat Chas',
    svc: '019.Sovanna',
    srl: '020.Siem Reap “Phsar Leu”',
    ktb: '021.Kbal Thnal',
    clb: '022.Chenla',
    hlb: '023.Phsar Heng Ly',
    tkb: '024.Tuol Kork',
    psb: '025.Pursat',
    skb: '026.Suon Ousahakam',
    cab: '027.Chbar Ampov',
    tab: '028.Takeo',
    trb: '029.Kratie',
    sub: '030.Suong',
    mmb: '031.Memut',
    tlb: '032.Thmor Kol',
    snb: '033.Skun',
    bvb: '034.Bavet',
    mrb: '035.Maung Russey',
    kb: '036.Kambol',
    kbb: '037.Kampong Thom',
    kkb: '038.Koh Kong',
    stb: '039.Stung Treng',
    ksb: '040.Kampong Speu',
    rkb: '041.Ratanakiri',
    smb: '042.Santhor mok',
    tpb: '043.Tuol Svay Prey',
    ttb: '044.Tuol Tumpoung',
    veb: '045.Vimean Ekareach',
    crb: '046.Chak Angre',
    pnb: '047.Prey Nup',
    tth: '048.Toek Thla ',
    pkl: '049.PreK Leap',
    pvb: '050.Preah Vihear',
    cdb: '051.Chamkar Daung',
    rsb: '052.Russey Keo',
    mkb: '053.Mondul Kiri',
    prb: '054.Prey Veng',
    omb: '055.Oddar Meanchey',
    svr: '056.Svay Rieng',
    bpb: '057.Borey Peanichkam Battambang ',
    nbb: '058.North Bridge',
    akb: '059.Angkor Arcade',
    olp: '060.Olympia',
    vkb: '061.Vithei Kampuchea Krom',
    khp: '063.KOH PICH',
    atb: '064.TRAM KAK',
    bkk: '065.Beoung Keng Kang',
    seb: '066.Saen Sokh',
    aem: '067.IFL',
    mcb: '068.Stuend Mean Chey ',
    amb: '069.Aeon Meanchey ',
  }

  const selectNationality = $('select[name=nationality]')
  const selectpickupBranch = $('#pickup-branch')

  let transformNational = Object.entries(country).map(([code, name]) => {
    return {
      id: code,
      text: `${code} ${name}`,
      selected: code === 'KH' ? true : false,
    }
  })
  selectNationality.select2({
    data: transformNational,
  })

  // let transformPickup = Object.entries(branch).map(([code, name]) => {
  //   return {
  //     id: code,
  //     text: name,
  //   }
  // })

  // selectpickupBranch.select2({
  //   data: transformPickup,
  // })
})
